class ValidationError(Exception):
    pass


class AuthenticationError(Exception):
    pass
